/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const afterAll: typeof import('vitest')['afterAll']
  const afterEach: typeof import('vitest')['afterEach']
  const assert: typeof import('vitest')['assert']
  const assertType: (typeof import('vitest'))['assertType']
  const beforeAll: typeof import('vitest')['beforeAll']
  const beforeEach: typeof import('vitest')['beforeEach']
  const bench: (typeof import('vitest'))['bench']
  const chai: typeof import('vitest')['chai']
  const createExpect: (typeof import('vitest'))['createExpect']
  const describe: typeof import('vitest')['describe']
  const expect: typeof import('vitest')['expect']
  const expectTypeOf: (typeof import('vitest'))['expectTypeOf']
  const getRunningMode: (typeof import('vitest'))['getRunningMode']
  const inject: (typeof import('vitest'))['inject']
  const isFirstRun: (typeof import('vitest'))['isFirstRun']
  const isWatchMode: (typeof import('vitest'))['isWatchMode']
  const it: typeof import('vitest')['it']
  const onTestFailed: (typeof import('vitest'))['onTestFailed']
  const onTestFinished: (typeof import('vitest'))['onTestFinished']
  const runOnce: (typeof import('vitest'))['runOnce']
  const should: (typeof import('vitest'))['should']
  const suite: typeof import('vitest')['suite']
  const test: typeof import('vitest')['test']
  const vi: typeof import('vitest')['vi']
  const vitest: typeof import('vitest')['vitest']
}
