name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      # `@pkgr/utils` is used by `@1stg/eslint-config`
      - name: Build
        run: yarn build

      - name: Lint and Test
        run: yarn run-s lint typecov test
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
